[build]
  base = "client"
  command = "npm run build"
  publish = "client/dist"

[build.environment]
  # Optional: you can set default env here, but it's recommended to set
  # VITE_API_BASE_URL in Netlify's UI to the production backend URL.
  # VITE_API_BASE_URL = "https://your-production-backend.example.com/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
